---
name: build

on:
  pull_request:

  push:
    branches:
      - main

  schedule:
    # run every month on the 10th at "night" time
    - cron:  '16 3 10 * *'

jobs:
  matrix-precommit:
    uses: ./.github/workflows/pre-commit.yml

  matrix-flatpak:
    uses: ./.github/workflows/build-flatpak.yml

  matrix-linux:
    uses: ./.github/workflows/build-linux.yml

  matrix-windows:
    uses: ./.github/workflows/build-windows.yml
