---
name: build

on:
  pull_request:

  push:
    branches:
      - main

  schedule:
    # run every month on the 10th at "night" time
    - cron:  '16 3 10 * *'

jobs:
  matrix-linux:
    uses: ./.github/workflows/build-linux.yml
