---
name: build

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  matrix-precommit:
    uses: ./.github/workflows/pre-commit.yml

  matrix-flatpak:
    uses: ./.github/workflows/build-flatpak.yml

  matrix-linux:
    uses: ./.github/workflows/build-linux.yml

  matrix-windows:
    uses: ./.github/workflows/build-windows.yml
